### ISSUE TITLE
OSX and npm install -g anvil-connect

### ISSUE THREAD

**Issue by ainthek** [anvilresearch/connect#362]
node --version
v8.1.3
$ npm --version
5.2.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1611

$ npm install -g anvil-connect
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated nodemailer@1.11.0: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

dtrace-provider@0.2.8 install /usr/local/lib/node_modules/anvil-connect/node_modules/pooling/node_modules/dtrace-provider
node-gyp rebuild
ACTION binding_gyp_libusdt_target_build_libusdt .
Building libusdt for x86_64
rm -f .gch
rm -f .o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -arch x86_64 -c -o usdt.o usdt.c
usdt.c:212:9: warning: implicit declaration of function 'usdt_dof_section_free' is invalid in C99 [-Wimplicit-function-declaration]
usdt_dof_section_free(&strtab);
^
usdt.c:238:9: warning: implicit declaration of function 'usdt_dof_file_free' is invalid in C99 [-Wimplicit-function-declaration]
usdt_dof_file_free(provider->file);
^
2 warnings generated.
gcc -O2 -arch x86_64 -c -o usdt_dof_file.o usdt_dof_file.c
gcc -arch x86_64 -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -arch x86_64 -c -o usdt_probe.o usdt_probe.c
gcc -O2 -arch x86_64 -c -o usdt_dof.o usdt_dof.c
gcc -O2 -arch x86_64 -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o
ranlib libusdt.a
TOUCH Release/obj.target/libusdt.stamp
CXX(target) Release/obj.target/DTraceProviderBindings/dtrace_provider.o
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:69:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value New(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:70:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value Fire(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:87:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value New(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:88:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value AddProbe(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:89:52: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value RemoveProbe(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:90:47: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value Enable(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:91:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value Disable(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:92:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value Fire(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
../dtrace_provider.cc:23:17: error: calling a protected constructor of class 'v8::HandleScope'
HandleScope scope;
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:846:13: note: declared protected here
V8_INLINE HandleScope() {}
^
../dtrace_provider.cc:25:55: error: cannot initialize a parameter of type 'v8::Isolate ' with an lvalue of type 'v8::Handlev8::Value
(const v8::internal::Arguments &)' (aka 'v8::Localv8::Value (const v8::internal::Arguments &)')
Local t = FunctionTemplate::New(DTraceProvider::New);
^~~~~~~~~~~~~~~~~~~
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:5132:16: note: passing argument to parameter 'isolate' here
Isolate isolate, FunctionCallback callback = 0,
^
../dtrace_provider.cc:26:58: error: 'New' is a private member of 'v8::PersistentBasev8::FunctionTemplate'
constructor_template = Persistent::New(t);
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:593:23: note: declared private here
V8_INLINE static T New(Isolate isolate, T* that);
^
../dtrace_provider.cc:26:28: error: too few arguments to function call, expected 2, have 1; did you mean 'DTraceProbe::New'?
constructor_template = Persistent::New(t);
^~~~~~~~~~
DTraceProbe::New
../dtrace_provider.h:69:34: note: 'DTraceProbe::New' declared here
static v8::Handlev8::Value New(const v8::Arguments& args);
^
../dtrace_provider.cc:27:25: error: member reference type 'Persistentv8::FunctionTemplate' is not a pointer; did you mean to use '.'?
constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
^
.
../dtrace_provider.cc:27:27: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate,
v8::NonCopyablePersistentTraitsv8::FunctionTemplate >'
constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
~~~~~~~~~~~~~~~~~~~~ ^
../dtrace_provider.cc:28:25: error: member reference type 'Persistentv8::FunctionTemplate' is not a pointer; did you mean to use '.'?
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
^
.
../dtrace_provider.cc:28:27: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate,
v8::NonCopyablePersistentTraitsv8::FunctionTemplate >'
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
~~~~~~~~~~~~~~~~~~~~ ^
../dtrace_provider.cc:28:48: error: no member named 'NewSymbol' in 'v8::String'
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
^
../dtrace_provider.cc:30:31: error: no viable conversion from 'Persistentv8::FunctionTemplate' to 'v8::Localv8::FunctionTemplate'
NODE_SET_PROTOTYPE_METHOD(constructor_template, "addProbe", DTraceProvider::AddProbe);
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
'Persistentv8::FunctionTemplate' to 'const v8::Localv8::FunctionTemplate &' for 1st argument
class Local {
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
'Persistentv8::FunctionTemplate' to 'v8::Localv8::FunctionTemplate &&' for 1st argument
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against 'Persistent'
V8_INLINE Local(Local that)
^
/Users/marcus/.node-gyp/8.1.3/include/node/node.h:286:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Localv8::FunctionTemplate recv,
^
../dtrace_provider.cc:31:31: error: no viable conversion from 'Persistentv8::FunctionTemplate' to 'v8::Localv8::FunctionTemplate'
NODE_SET_PROTOTYPE_METHOD(constructor_template, "removeProbe", DTraceProvider::RemoveProbe);
^~~~~~~~~~~~~~~~~~~~
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
'Persistentv8::FunctionTemplate' to 'const v8::Localv8::FunctionTemplate &' for 1st argument
class Local {
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
'Persistentv8::FunctionTemplate' to 'v8::Localv8::FunctionTemplate &&' for 1st argument
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against 'Persistent'
V8_INLINE Local(Local that)
^
/Users/marcus/.node-gyp/8.1.3/include/node/node.h:286:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Localv8::FunctionTemplate recv,
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack at emitTwo (events.js:125:13)
gyp ERR! stack at ChildProcess.emit (events.js:213:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/anvil-connect/node_modules/pooling/node_modules/dtrace-provider
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

dtrace-provider@0.2.8 install /usr/local/lib/node_modules/anvil-connect/node_modules/ldapauth-fork/node_modules/dtrace-provider
node-gyp rebuild
ACTION binding_gyp_libusdt_target_build_libusdt .
Building libusdt for x86_64
rm -f .gch
rm -f .o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -arch x86_64 -c -o usdt.o usdt.c
usdt.c:212:9: warning: implicit declaration of function 'usdt_dof_section_free' is invalid in C99 [-Wimplicit-function-declaration]
usdt_dof_section_free(&strtab);
^
usdt.c:238:9: warning: implicit declaration of function 'usdt_dof_file_free' is invalid in C99 [-Wimplicit-function-declaration]
usdt_dof_file_free(provider->file);
^
2 warnings generated.
gcc -O2 -arch x86_64 -c -o usdt_dof_file.o usdt_dof_file.c
gcc -arch x86_64 -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -arch x86_64 -c -o usdt_probe.o usdt_probe.c
gcc -O2 -arch x86_64 -c -o usdt_dof.o usdt_dof.c
gcc -O2 -arch x86_64 -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o
ranlib libusdt.a
TOUCH Release/obj.target/libusdt.stamp
CXX(target) Release/obj.target/DTraceProviderBindings/dtrace_provider.o
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:69:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value New(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:70:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value Fire(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:87:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value New(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:88:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value AddProbe(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:89:52: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value RemoveProbe(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:90:47: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value Enable(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:91:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value Disable(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:92:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
static v8::Handlev8::Value Fire(const v8::Arguments& args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
^
../dtrace_provider.cc:23:17: error: calling a protected constructor of class 'v8::HandleScope'
HandleScope scope;
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:846:13: note: declared protected here
V8_INLINE HandleScope() {}
^
../dtrace_provider.cc:25:55: error: cannot initialize a parameter of type 'v8::Isolate ' with an lvalue of type 'v8::Handlev8::Value
(const v8::internal::Arguments &)' (aka 'v8::Localv8::Value (const v8::internal::Arguments &)')
Local t = FunctionTemplate::New(DTraceProvider::New);
^~~~~~~~~~~~~~~~~~~
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:5132:16: note: passing argument to parameter 'isolate' here
Isolate isolate, FunctionCallback callback = 0,
^
../dtrace_provider.cc:26:58: error: 'New' is a private member of 'v8::PersistentBasev8::FunctionTemplate'
constructor_template = Persistent::New(t);
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:593:23: note: declared private here
V8_INLINE static T New(Isolate isolate, T* that);
^
../dtrace_provider.cc:26:28: error: too few arguments to function call, expected 2, have 1; did you mean 'DTraceProbe::New'?
constructor_template = Persistent::New(t);
^~~~~~~~~~
DTraceProbe::New
../dtrace_provider.h:69:34: note: 'DTraceProbe::New' declared here
static v8::Handlev8::Value New(const v8::Arguments& args);
^
../dtrace_provider.cc:27:25: error: member reference type 'Persistentv8::FunctionTemplate' is not a pointer; did you mean to use '.'?
constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
^
.
../dtrace_provider.cc:27:27: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate,
v8::NonCopyablePersistentTraitsv8::FunctionTemplate >'
constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
~~~~~~~~~~~~~~~~~~~~ ^
../dtrace_provider.cc:28:25: error: member reference type 'Persistentv8::FunctionTemplate' is not a pointer; did you mean to use '.'?
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
^
.
../dtrace_provider.cc:28:27: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate,
v8::NonCopyablePersistentTraitsv8::FunctionTemplate >'
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
~~~~~~~~~~~~~~~~~~~~ ^
../dtrace_provider.cc:28:48: error: no member named 'NewSymbol' in 'v8::String'
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
^
../dtrace_provider.cc:30:31: error: no viable conversion from 'Persistentv8::FunctionTemplate' to 'v8::Localv8::FunctionTemplate'
NODE_SET_PROTOTYPE_METHOD(constructor_template, "addProbe", DTraceProvider::AddProbe);
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
'Persistentv8::FunctionTemplate' to 'const v8::Localv8::FunctionTemplate &' for 1st argument
class Local {
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
'Persistentv8::FunctionTemplate' to 'v8::Localv8::FunctionTemplate &&' for 1st argument
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against 'Persistent'
V8_INLINE Local(Local that)
^
/Users/marcus/.node-gyp/8.1.3/include/node/node.h:286:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Localv8::FunctionTemplate recv,
^
../dtrace_provider.cc:31:31: error: no viable conversion from 'Persistentv8::FunctionTemplate' to 'v8::Localv8::FunctionTemplate'
NODE_SET_PROTOTYPE_METHOD(constructor_template, "removeProbe", DTraceProvider::RemoveProbe);
^~~~~~~~~~~~~~~~~~~~
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
'Persistentv8::FunctionTemplate' to 'const v8::Localv8::FunctionTemplate &' for 1st argument
class Local {
^
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
'Persistentv8::FunctionTemplate' to 'v8::Localv8::FunctionTemplate &&' for 1st argument
/Users/marcus/.node-gyp/8.1.3/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against 'Persistent'
V8_INLINE Local(Local that)
^
/Users/marcus/.node-gyp/8.1.3/include/node/node.h:286:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Localv8::FunctionTemplate recv,
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack at emitTwo (events.js:125:13)
gyp ERR! stack at ChildProcess.emit (events.js:213:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/anvil-connect/node_modules/ldapauth-fork/node_modules/dtrace-provider
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.2.8 (node_modules/anvil-connect/node_modules/pooling/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.2.8 install: node-gyp rebuild
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.2.8 (node_modules/anvil-connect/node_modules/ldapauth-fork/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.2.8 install: node-gyp rebuild
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

anvil-connect@0.1.59
added 2 packages and updated 1 package in 11.544s

**Comment by ainthek** [comment]
Please any feedback ?

**Comment by christiansmith** [comment]
@ainthek you'll want to install `anvil-connect-cli`, not `anvil-connect` globally. 

Apologies, we've been spread thin and dependencies are out of date, but @LegallyGeek has kindly joined the core team and is working on bringing everything current. 

Thanks for being patient.

**Comment by LegallyGeek** [comment]
@ainthek I'm hoping to have an updated Connect in the next few days.  I'll ping you when that's up.

**Comment by ainthek** [comment]
Danke

**Comment by ainthek** [comment]
@christiansmith BTW chris, this page needs to be fixed then: https://github.com/anvilresearch/connect-docs/blob/master/getting-started.md it has text
npm install -g anvil-connect
