### ISSUE TITLE
Standard OAuth2 protocol require error

### ISSUE THREAD

**Issue by tomkersten** [anvilresearch/connect#74]
When trying to deploy (to Modulus) with the most recent code, I get the following error:

```
/mnt/data/2/node_modules/anvil-connect/protocols/index.js:30
      throw new Error("Can't find custom protocol: " + protocol);
            ^
Error: Can't find custom protocol: OAuth2
    at Object.initialize (/mnt/data/2/node_modules/anvil-connect/protocols/index.js:30:13)
    at /mnt/data/2/node_modules/anvil-connect/boot/passport.js:40:30
    at Array.forEach (native)
    at module.exports (/mnt/data/2/node_modules/anvil-connect/boot/passport.js:35:37)
    at Object.<anonymous> (/mnt/data/2/node_modules/anvil-connect/server.js:16:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I don't have a custom OAuth2 protocol, but it is erroring out when [requiring the one that ships](https://github.com/christiansmith/anvil-connect/blob/master/protocols/OAuth2.js#L12) with Anvil Connect.

This boots fine locally. I thought _maybe_ the capital "M" was causing a problem, but...when I tried swapping that out with `require("modinha");`...that gave an error related to a symbol lookup...which I believe has to do w/ compiled modules for the encryption libraries (I suspect this was why it has a capital "M" to start with).

Any advice on how to proceed?

**Comment by christiansmith** [comment]
The uppercase M is a mistake in the code, but one that didn't break anything in my environments. We do need to change it. Can you share the details of the symbol lookup error?

**Comment by tomkersten** [comment]
Sure. When changing the 'M' to an 'm' in that require line...the error changes to:

```
/mnt/data/1/node_modules/jsjws/node_modules/ursa/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /mnt/data/1/node_modules/jsjws/node_modules/ursa/build/Release/ursaNative.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/mnt/data/1/node_modules/jsjws/node_modules/ursa/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/mnt/data/1/node_modules/jsjws/node_modules/ursa/lib/ursa.js:18:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[2015-03-24T00:00:46.418Z] Application CRASH detected. Exit code 8.
[2015-03-24T00:00:47.297Z] Application restarted.
npm WARN package.json modinha-redis@0.0.15 No repository field.
npm WARN package.json uri-js@1.4.2 No repository field.
[2015-03-24T00:00:48.461Z] Application stopped.
INFO: Main file specified in package.json: server.js
INFO: Starting application.
```

**Comment by christiansmith** [comment]
@tomkersten I believe this was eventually resolved, but we never followed up on the issue. Please reopen if necessary. Thanks!
